### ISSUE TITLE
Adding Actions

### ISSUE THREAD

**Issue by dev-nolant** [thevalleyy/CustomCommands#2]
**Describe the feature you want to request**
A parse of [[Actions]] to allow me to do something like /server SERVER_NAME for the user

**What's the reason for the request?**
Would extend the usability of this plugin

**Additional context**
![image](https://github.com/user-attachments/assets/60fa0dc9-d33a-44a5-8724-2ed9f662f24a)

**Comment by thevalleyy** [comment]
I'll look over it when I've got the time :)

**Comment by dev-nolant** [comment]
Sounds good! I plan on looking into it today as well, so I'll let you know if I add anything significant!

**Comment by thevalleyy** [comment]
Just to let you know, yes, I still have your issue on my mind. Tests and other projects are currently more important, but in a month or so, I will take the time to update cc.

**Comment by Mailootje** [comment]
This is the new config for example:

```toml
# Command Configuration

# Enabled?
Enabled = true

# This is the command name that will be used to call the command in the chat
Name = "survival"

# These are the aliases. Empty the array if you don't want any aliases, like so: Aliases = []
Aliases = []

# This is the description of the command that will be displayed in the help command
Description = "Switches to the Survival server."

# This is the permission required to use the command. Leave empty for no permission
Permission = "customcommands.survival"

# This is the response that will be sent when the command is called. Leave empty for no response
Response = "<green>Switching to Survival server..."

# Add the plugins Prefix configured in config.toml to the response message
UsePrefix = true

# This is the cooldown of the command in seconds
Cooldown = 3

# Proxy execution (if supported by the plugin)
ProxyCommand = true

# This executes the actual server switch command (Velocity-compatible)
ExecuteCommand = "send {player} survival"

# The name of the backend server (must match the name as registered in Velocity)
TargetServer = "survival"
```
